import Badge from "../components/Badge";
import BaseAlert from "../components/BaseAlert";
import BaseButton from "../components/BaseButton";
import BaseCheckbox from "../components/BaseCheckbox";
import BaseInput from "../components/BaseInput";
import BaseDropdown from "../components/BaseDropdown";
import BaseNav from "../components/BaseNav";
import BasePagination from "../components/BasePagination";
import BaseProgress from "../components/BaseProgress";
import BaseRadio from "../components/BaseRadio";
import BaseSlider from "../components/BaseSlider";
import BaseSwitch from "../components/BaseSwitch";
import BaseTable from "../components/BaseTable";
import BaseHeader from "../components/BaseHeader";
import Card from "../components/Card";
import StatsCard from "../components/StatsCard";
import Modal from "../components/Modal";
import TabPane from "../components/Tabs/TabPane";
import Tabs from "../components/Tabs/Tabs";
import Pagination from "../components/Pagination";
import PaperTable from "../components/PaperTable";
import CheckButtons from "../components/CheckButtons";
import BankReconButtons from "../components/BankReconButtons";
import CardWidget from "../components/CardWidgets.vue";
import NewCheck from "../views/Banks/CheckBookWriter";
import CheckList from "../views/Banks/BankChecks";
import PrintCheck from "../views/Banks/CheckVoucher";
import BankAccounts from "../views/Banks/BankAccounts";
import CheckSeries from "../views/Banks/CheckSeries";
import CheckPayee from "../views/Banks/Suppliers";
import BankAccountFund from "../views/Banks/bankAccountFunds";
import BankAccountBalance from "../views/Banks/BankAccountBalance";
import BankAccountWithdrawal from "../views/Banks/bankAccountWithdrawals";
import NewReimbursementAdmin from "../views/Expenses/NewReimbursementAdmin";
import NewReimbursementUser from "../views/Expenses/NewReimbursementUser";
import AdminReimbursementList from "../views/Expenses/AdminReimbursementList";
import UserReimbursementList from "../views/Expenses/UserReimbursementList";
import NewPaymentAdvice from "../views/Sales/NewPaymentAdvice";
import PaymentAdviceList from "../views/Sales/PaymentAdviceList";
import ReimSummary from "../views/Expenses/ReimbursementSummary";
import ReimDesc from "../views/Settings/ReimbursementDesc";
import LiquidationDesc from "../views/Settings/LiquidationDesc";
import NewPettyCash from "../views/Expenses/NewPettyCash";
import NewPurchaseOrder from "../views/Sales/NewPurchaseOrder";
import NewSalesInvoice from "../views/Sales/NewSalesInvoice";
import NewDeliveryReceipt from "../views/Sales/NewDeliveryReceipt";
import EWalletAccount from "../views/Maintenance/EWalletAccount";
import NewETransaction from "../views/Vouchers/NewETransaction";
import CashAdvanceType from "../views/Expenses/CashAdvanceType";
import ForClearingChecks from "../views/Banks/ForClearingChecks";
import NearlyClearingChecks from "../views/Banks/NearlyClearingChecks";
import PostDatedChecks from "../views/Banks/PostDatedChecks";
import CashDisbursementType from "../views/Disbursements/CashDisbursementType";
import RemittanceDisbursementType from "../views/Disbursements/RemittanceDisbursementType";
import CheckVoucherParticular from "../views/Banks/CheckVoucherParticular";
import NewCheckVoucherParticular from "../components/CheckVoucherParticulars/NewCheckVoucherParticular";
import EditCheckVoucherParticular from "../components/CheckVoucherParticulars/EditCheckVoucherParticular";

export default {
  install(Vue) {
    Vue.component(Badge.name, Badge);
    Vue.component(BaseAlert.name, BaseAlert);
    Vue.component(BaseButton.name, BaseButton);
    Vue.component(BaseInput.name, BaseInput);
    Vue.component(BaseNav.name, BaseNav);
    Vue.component(BaseDropdown.name, BaseDropdown);
    Vue.component(BaseCheckbox.name, BaseCheckbox);
    Vue.component(BasePagination.name, BasePagination);
    Vue.component(BaseProgress.name, BaseProgress);
    Vue.component(BaseRadio.name, BaseRadio);
    Vue.component(BaseSlider.name, BaseSlider);
    Vue.component(BaseSwitch.name, BaseSwitch);
    Vue.component(BaseTable.name, BaseTable);
    Vue.component(BaseHeader.name, BaseHeader);
    Vue.component(Card.name, Card);
    Vue.component(StatsCard.name, StatsCard);
    Vue.component(Modal.name, Modal);
    Vue.component(TabPane.name, TabPane);
    Vue.component(Tabs.name, Tabs);
    Vue.component(Pagination.name, Pagination);
    Vue.component(PaperTable.name, PaperTable);
    Vue.component(CheckButtons.name, CheckButtons);
    Vue.component(BankReconButtons.name, BankReconButtons);
    Vue.component(CardWidget.name, CardWidget);
    Vue.component(NewCheck.name, NewCheck);
    Vue.component(CheckList.name, CheckList);
    Vue.component(PrintCheck.name, PrintCheck);
    Vue.component(BankAccounts.name, BankAccounts);
    Vue.component(CheckSeries.name, CheckSeries);
    Vue.component(CheckPayee.name, CheckPayee);
    Vue.component(BankAccountFund.name, BankAccountFund);
    Vue.component(BankAccountBalance.name, BankAccountBalance);
    Vue.component(BankAccountWithdrawal.name, BankAccountWithdrawal);
    Vue.component(NewReimbursementAdmin.name, NewReimbursementAdmin);
    Vue.component(NewReimbursementUser.name, NewReimbursementUser);
    Vue.component(AdminReimbursementList.name, AdminReimbursementList);
    Vue.component(UserReimbursementList.name, UserReimbursementList);
    Vue.component(NewPaymentAdvice.name, NewPaymentAdvice);
    Vue.component(PaymentAdviceList.name, PaymentAdviceList);
    Vue.component(ReimSummary.name, ReimSummary);
    Vue.component(ReimDesc.name, ReimDesc);
    Vue.component(LiquidationDesc.name, LiquidationDesc);
    Vue.component(NewPettyCash.name, NewPettyCash);
    Vue.component(NewPurchaseOrder.name, NewPurchaseOrder);
    Vue.component(NewSalesInvoice.name, NewSalesInvoice);
    Vue.component(NewDeliveryReceipt.name, NewDeliveryReceipt);
    Vue.component(EWalletAccount.name, EWalletAccount);
    Vue.component(NewETransaction.name, NewETransaction);
    Vue.component(CashAdvanceType.name, CashAdvanceType);
    Vue.component(ForClearingChecks.name, ForClearingChecks);
    Vue.component(NearlyClearingChecks.name, NearlyClearingChecks);
    Vue.component(PostDatedChecks.name, PostDatedChecks);
    Vue.component(CashDisbursementType.name, CashDisbursementType);
    Vue.component(RemittanceDisbursementType.name, RemittanceDisbursementType);
    Vue.component(CheckVoucherParticular.name, CheckVoucherParticular);
    Vue.component(NewCheckVoucherParticular.name, NewCheckVoucherParticular);
    Vue.component(EditCheckVoucherParticular.name, EditCheckVoucherParticular);
  }
};
